/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SaloreeControlRouteImport } from './routes/saloree-control'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as SellerThemesRouteImport } from './routes/seller.themes'
import { Route as SellerThemeCustomizerRouteImport } from './routes/seller.theme-customizer'
import { Route as SellerStoreRouteImport } from './routes/seller.store'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerPreferencesRouteImport } from './routes/seller.preferences'
import { Route as SellerPagesRouteImport } from './routes/seller.pages'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerNavigationRouteImport } from './routes/seller.navigation'
import { Route as SellerDiscountsRouteImport } from './routes/seller.discounts'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerContentRouteImport } from './routes/seller.content'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SaloreeControlContentRouteImport } from './routes/saloree-control.content'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SaloreeControlRoute = SaloreeControlRouteImport.update({
  id: '/saloree-control',
  path: '/saloree-control',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerThemesRoute = SellerThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => SellerRoute,
} as any)
const SellerThemeCustomizerRoute = SellerThemeCustomizerRouteImport.update({
  id: '/theme-customizer',
  path: '/theme-customizer',
  getParentRoute: () => SellerRoute,
} as any)
const SellerStoreRoute = SellerStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPreferencesRoute = SellerPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPagesRoute = SellerPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNavigationRoute = SellerNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDiscountsRoute = SellerDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerContentRoute = SellerContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const SaloreeControlContentRoute = SaloreeControlContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => SaloreeControlRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/saloree-control': typeof SaloreeControlRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/saloree-control/content': typeof SaloreeControlContentRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/content': typeof SellerContentRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/discounts': typeof SellerDiscountsRoute
  '/seller/navigation': typeof SellerNavigationRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pages': typeof SellerPagesRoute
  '/seller/preferences': typeof SellerPreferencesRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/store': typeof SellerStoreRoute
  '/seller/theme-customizer': typeof SellerThemeCustomizerRoute
  '/seller/themes': typeof SellerThemesRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/saloree-control': typeof SaloreeControlRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/saloree-control/content': typeof SaloreeControlContentRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/content': typeof SellerContentRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/discounts': typeof SellerDiscountsRoute
  '/seller/navigation': typeof SellerNavigationRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pages': typeof SellerPagesRoute
  '/seller/preferences': typeof SellerPreferencesRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/store': typeof SellerStoreRoute
  '/seller/theme-customizer': typeof SellerThemeCustomizerRoute
  '/seller/themes': typeof SellerThemesRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/saloree-control': typeof SaloreeControlRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/saloree-control/content': typeof SaloreeControlContentRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/content': typeof SellerContentRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/discounts': typeof SellerDiscountsRoute
  '/seller/navigation': typeof SellerNavigationRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pages': typeof SellerPagesRoute
  '/seller/preferences': typeof SellerPreferencesRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/store': typeof SellerStoreRoute
  '/seller/theme-customizer': typeof SellerThemeCustomizerRoute
  '/seller/themes': typeof SellerThemesRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/register'
    | '/saloree-control'
    | '/seller'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/stores'
    | '/admin/users'
    | '/auth/callback'
    | '/categories/$slug'
    | '/products/$slug'
    | '/saloree-control/content'
    | '/seller/analytics'
    | '/seller/content'
    | '/seller/customers'
    | '/seller/discounts'
    | '/seller/navigation'
    | '/seller/orders'
    | '/seller/pages'
    | '/seller/preferences'
    | '/seller/products'
    | '/seller/store'
    | '/seller/theme-customizer'
    | '/seller/themes'
    | '/stores/$slug'
    | '/admin/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/register'
    | '/saloree-control'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/stores'
    | '/admin/users'
    | '/auth/callback'
    | '/categories/$slug'
    | '/products/$slug'
    | '/saloree-control/content'
    | '/seller/analytics'
    | '/seller/content'
    | '/seller/customers'
    | '/seller/discounts'
    | '/seller/navigation'
    | '/seller/orders'
    | '/seller/pages'
    | '/seller/preferences'
    | '/seller/products'
    | '/seller/store'
    | '/seller/theme-customizer'
    | '/seller/themes'
    | '/stores/$slug'
    | '/admin'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/marketplace'
    | '/orders'
    | '/register'
    | '/saloree-control'
    | '/seller'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/stores'
    | '/admin/users'
    | '/auth/callback'
    | '/categories/$slug'
    | '/products/$slug'
    | '/saloree-control/content'
    | '/seller/analytics'
    | '/seller/content'
    | '/seller/customers'
    | '/seller/discounts'
    | '/seller/navigation'
    | '/seller/orders'
    | '/seller/pages'
    | '/seller/preferences'
    | '/seller/products'
    | '/seller/store'
    | '/seller/theme-customizer'
    | '/seller/themes'
    | '/stores/$slug'
    | '/admin/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  SaloreeControlRoute: typeof SaloreeControlRouteWithChildren
  SellerRoute: typeof SellerRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StoresSlugRoute: typeof StoresSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saloree-control': {
      id: '/saloree-control'
      path: '/saloree-control'
      fullPath: '/saloree-control'
      preLoaderRoute: typeof SaloreeControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/themes': {
      id: '/seller/themes'
      path: '/themes'
      fullPath: '/seller/themes'
      preLoaderRoute: typeof SellerThemesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/theme-customizer': {
      id: '/seller/theme-customizer'
      path: '/theme-customizer'
      fullPath: '/seller/theme-customizer'
      preLoaderRoute: typeof SellerThemeCustomizerRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/store': {
      id: '/seller/store'
      path: '/store'
      fullPath: '/seller/store'
      preLoaderRoute: typeof SellerStoreRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/preferences': {
      id: '/seller/preferences'
      path: '/preferences'
      fullPath: '/seller/preferences'
      preLoaderRoute: typeof SellerPreferencesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/pages': {
      id: '/seller/pages'
      path: '/pages'
      fullPath: '/seller/pages'
      preLoaderRoute: typeof SellerPagesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/navigation': {
      id: '/seller/navigation'
      path: '/navigation'
      fullPath: '/seller/navigation'
      preLoaderRoute: typeof SellerNavigationRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/discounts': {
      id: '/seller/discounts'
      path: '/discounts'
      fullPath: '/seller/discounts'
      preLoaderRoute: typeof SellerDiscountsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/content': {
      id: '/seller/content'
      path: '/content'
      fullPath: '/seller/content'
      preLoaderRoute: typeof SellerContentRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/saloree-control/content': {
      id: '/saloree-control/content'
      path: '/content'
      fullPath: '/saloree-control/content'
      preLoaderRoute: typeof SaloreeControlContentRouteImport
      parentRoute: typeof SaloreeControlRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SaloreeControlRouteChildren {
  SaloreeControlContentRoute: typeof SaloreeControlContentRoute
}

const SaloreeControlRouteChildren: SaloreeControlRouteChildren = {
  SaloreeControlContentRoute: SaloreeControlContentRoute,
}

const SaloreeControlRouteWithChildren = SaloreeControlRoute._addFileChildren(
  SaloreeControlRouteChildren,
)

interface SellerRouteChildren {
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerContentRoute: typeof SellerContentRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerDiscountsRoute: typeof SellerDiscountsRoute
  SellerNavigationRoute: typeof SellerNavigationRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPagesRoute: typeof SellerPagesRoute
  SellerPreferencesRoute: typeof SellerPreferencesRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerStoreRoute: typeof SellerStoreRoute
  SellerThemeCustomizerRoute: typeof SellerThemeCustomizerRoute
  SellerThemesRoute: typeof SellerThemesRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerContentRoute: SellerContentRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerDiscountsRoute: SellerDiscountsRoute,
  SellerNavigationRoute: SellerNavigationRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPagesRoute: SellerPagesRoute,
  SellerPreferencesRoute: SellerPreferencesRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerStoreRoute: SellerStoreRoute,
  SellerThemeCustomizerRoute: SellerThemeCustomizerRoute,
  SellerThemesRoute: SellerThemesRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  SaloreeControlRoute: SaloreeControlRouteWithChildren,
  SellerRoute: SellerRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StoresSlugRoute: StoresSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
